version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
    command:  mongod --replSet deneme